export interface Product {
    Producent? : string,
    Matryca? : string,
    Rozdzielczosc?: string,
    TypMatrycy?: string,
    DotykowyEkran?: string,
    CPU? : string,
    IloscRdzeni? : string,
    MHZ? : string,
    RAM? : string,
    PojemnoscDysku? : string,
    RodzajDysku? : string,
    GPU? : string,
    VRAM? : string,
    SystemOperacyjny? : string,
    Naped? : string,
}